# Generated by Django 2.0 on 2020-02-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_classic',
            field=models.BooleanField(default=False, verbose_name='是否是经典课程'),
        ),
    ]
